### ISSUE TITLE
Investigate "FE Block" feature

### ISSUE THREAD

**Issue by ew-andrew-sus** [ytgov/yukon-ca#373]
**Description:**
See "fe_block_settings" and "fe_block_boxes" configs

**Task:**
Migrate "FE Block"

**Deliverable:**
"fe_block_settings" and "fe_block_boxes" in "FE Block" feature should be migrated and placed like in D7

**Comment by leeomara** [comment]
I believe this is about some block-related Features Extra functionality/config that could/should be migrated to D10.

**Comment by leeomara** [comment]
On D7, I see the following custom Feature modules declare a dependency on Features Extra

* yg_site_wide_alert
* yg_in_page_alerts
* yg_blog
* sidebar_menu_block
* yg_landing_page_level_2
* yg_topics_page
* yg_news
* yg_search
* yg_engagements
* yg_campground_content_type

**Comment by adrianrylski** [comment]
@leeomara We will have a look and I will get back to you. I have added an investigation ticket for it. Thx

**Comment by adrianrylski** [comment]
@leeomara and @lgontard We did review all blocks. Please find enclosed spreadsheet with the inventory.

**Comment by adrianrylski** [comment]
If you want me to make the first pass on it, @leeomara , let me know. Happy too.

**Comment by leeomara** [comment]
Hi @adrianrylski,

Sorry it took so long to review and respond. Here is our feedback

Line 5 (views-40241e478e530bbd637cada178df7385): 
  - LO: I see the block configured, but can't see it ever rendered anywhere.

- Line 6 (views-63ff0846caed39d1e826792b24786766): 
  - LO: RE 1 & 3: Prod D7 is the reference "good" copy, so if something doesn’t exist there, we don't need to worry about it.
  - LG: the taxonomy list in Prod is more up to date. The one in UAT is not. But issue 179 in GitLab to has the complete list of subcategories in Eng and Fre French taxonomy for subcategories. This issue 167 in GitLab includes some translation issues such as translation of subcategories."

Line 8 (campground_availability_legend): 
  - LO how will/would we update the "Only the listed pages" block configuration to account for the changing NID?

Line 23 (views-in_page_alerts-block): 
  - LO: Our testing of in-page alerts didn't identify a problem. Are there behavious/conditions that we maybe didn't test or consider?
  - LG: We want inpage alerts to appear on all content types, except the home page. This was a need identified during COVID-19.

Line 27 (custom_search_blocks-1): 
  - LO: Search, as implemented looks good. Not clear if/what functionality is "missing" due to not migrating this.

**Comment by leeomara** [comment]
Closing, as this issue has lost it's significance.
